# -*- coding: utf-8 -*-
"""A competitor with NO colour preference crashed the pairing.

`crosstable_dutch.color_preference` returns "w2"/"b2", "w1"/"b1", "w0"/"b0" -- and "nc", for a
competitor with no colour preference at all. That last is not a corner case invented for a test:
it is what a player with no games played *at the board* gets, and a small field carrying byes or
forfeits reaches that state naturally by its third round.

`crosstabledutch.update_edge` then took the first character of the preference and looked it up in
a table with no entry for it:

    opp = {"w": "bb", "b": "ww", " ": "nc"}[acop[0]]     # acop == "nc"  ->  KeyError: 'n'

and the engine died with `KeyError: 'n'` while pairing a perfectly legal tournament.

The value was never used. It is read only inside the branch immediately below, which cannot be
entered unless the preference begins "w" or "b" -- and which recomputes it from its own two-entry
table anyway. So the line computed a value it did not need and crashed the engine doing it.

Reaching it needs three things at once, which is why an ordinary corpus does not: a heterogeneous
bracket, a topscorer in it (the whole C10/C11 block is guarded on `a["top"] or b["top"]`), and a
competitor with no colour preference. The fixture below is one such position -- eight players,
two rounds played, round three to pair -- reduced from a tournament generated by bbpPairings.
"""
import os

import pytest

import trf2json
from pairing import pairing
from pairingdutch import pairing_dutch

FIXTURE = os.path.join(os.path.dirname(__file__), "fixtures", "no_colour_preference.trf")


def read(path):
    reader = trf2json.trf2json()
    with open(path, encoding="utf-8") as handle:
        reader.parse_file(handle.read(), 0)
    return reader.get_tournament(1)


class TestColourPreferenceIsTotal:
    """Every value color_preference() can return, update_edge() must be able to consume."""

    def test_a_competitor_with_no_played_games_has_no_colour_preference(self):
        from crosstabledutch import crosstable_dutch

        assert crosstable_dutch.color_preference(None, 0, "") == "nc"


class TestTheCrashingPositionPairs:
    """The regression, stated as behaviour: this tournament used to raise KeyError: 'n'."""

    def test_round_three_can_be_paired(self):
        tournament = read(FIXTURE)
        tournament["topColor"] = "w"
        params = {"experimental": [], "verbose": 0, "rank": False, "top_color": "w"}
        engine = pairing_dutch(tournament, 3, params)

        brackets = engine.compute_pairing(False, 0)

        pairs = [p for bracket in brackets if bracket and "pairs" in bracket for p in bracket["pairs"]]
        assert pairs, "the engine returned no pairing at all"

        # Eight players, so four boards and no bye; nobody appears twice.
        seated = [cid for pair in pairs for cid in (pair["w"], pair["b"]) if cid]
        assert len(pairs) == 4
        assert sorted(seated) == list(range(1, 9))
